algorithm_description: Generate cloud-free temporal mosaics from HLS data
algorithm_name: hls-composite
algorithm_version: dev
build_command: hls-composite/build-env.sh
disk_space: 8GB
docker_container_url: mas.maap-project.org/root/maap-workspaces/custom_images/maap_base:v4.3.0
inputs:
  config: []
  file: []
  positional:
  - default: ''
    description: ' start datetime for HLS STAC query in YYYY-mm-ddTHH:MM:SSZ format'
    name: start_datetime
    required: true
  - default: ''
    description: ' end datetime for HLS STAC query in YYYY-mm-ddTHH:MM:SSZ format'
    name: end_datetime
    required: true
  - default: ''
    description: space-separated bounding box coordinates in CRS coordinates (xmin
      ymin xmax ymax)
    name: bbox
    required: false
  - default: ''
    description: coordinate reference system (e.g. epsg:5070)
    name: crs
    required: false
  - default: ''
    description: output multiband cog file name if merging assets
    name: output_name
    required: false
  - default: ''
    description: A georeferenced vector file of the study area if not using bbox and crs options
    name: aoi
    required: false
  - default: ''
    description: composite type should be one of median, maxndvi, or qndvi.
    name: composite_type
    required: false
  - default: ''
    description: quantile of ndvi if composite_type is qndvi
    name: q
    required: false
  - default: ''
    description: max number of stac assets (items) to be merged
    name: lim
    required: false
  - default: ''
    description: Build catolog of composite assets, mutually exclusive with output_name
    name: catalog
    required: false
  - default: ''
    description: list of space separated indices (lower case), e.g, ndvi, nbr, evi, ...
    name: indices
    required: false


queue: maap-dps-worker-16gb
repository_url: https://github.com/aliz237/hls-composite.git
run_command: hls-composite/run.sh
